name: Tests (conda-forge)

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: pwsh
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-2022, windows-2025 ]
        python-version: ['3.9', '3.13']

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        channels: conda-forge
        channel-priority: strict
        activate-environment: test_windows_numpy

    - name: Install dependencies
      run: |
        conda info
        conda install -c conda-forge numpy "llvm-openmp<21" pytest
        conda list

    - name: Run unit tests
      run: |
        python -m pytest -vv .

